### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRCrashlytics ...

### ISSUE THREAD

**Issue by cohen72** [akaffenberger/firebase-ios-sdk-xcframeworks#43] opened 2022-08-31 11:16 UTC
I've added this package as a dependency to another swift package I have created `MyPackage`, and from Xcode's Project/ProjectDependency settings, I've added `https://github.com/me/mypackage` as a dependency.

Now, when attempting to compile my project, I receive the following errors:

```
Build target MyPackage
Package MyPackage | Configuration Staging | Destination My iPhone | SDK iOS 15.5
Link MyPackage_PackageProduct (arm64)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRCrashlytics", referenced from:
      objc-class-ref in NanitCore.o
  "_OBJC_CLASS_$_FIRRemoteConfigSettings", referenced from:
      objc-class-ref in NanitCore.o
  "_OBJC_CLASS_$_FIRRemoteConfig", referenced from:
      objc-class-ref in NanitCore.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

![image](https://user-images.githubusercontent.com/1394233/187665417-99b8cf6f-bf3e-44ac-98ce-6775f2b1bc75.png)

I'm not sure what I'm missing, but it seems that when attempting to compile `MyPackage` which has `firebase-ios-sdk-xcframeworks` as a dependency, it fails ... Any ideas?

**Comment by akaffenberger** [comment] 2022-10-06 01:57
Would you be able to share what the Package.swift file looks like for `MyPackage`? 

I just tried a small example and wasn't able to reproduce. I created a package called MyLibrary that imports and uses FirebaseCrashlytics, FirebaseRemoteConfig, and GoogleSignIn. I then added MyLibrary to an xcode project, used the test class I created, and was able to compile and run.

**Comment by akaffenberger** [comment] 2022-12-16 20:25
Closing until further information is received from OP

**Closed by akaffenberger** 2022-12-16 20:25 UTC
